version: '3.7'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5434:5432
    env_file:
      backend/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - backend/.env
  nginx:
    image: nginx:1.15

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot

    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    command: certonly --noninteractive --webroot --webroot-path=/var/www/certbot --email zymlagzom@gmail.com --agree-tos --no-eff-email -d zymzom.tk
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - /var/www/certbot:/var/www/certbot
